name: Run PowerShell Script

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * *' # 每天午夜运行

jobs:
  run-powershell-script:
    runs-on: windows-latest # 使用 Windows 环境运行 PowerShell 脚本

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PowerShell script
        run: |
          .\generate_version_info.ps1

      - name: Upload JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: version_info.json
          path: version_info.json
